# Generated by Django 3.2.8 on 2021-10-26 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilestatus',
            old_name='userprofile',
            new_name='user_profile',
        ),
    ]
